### ISSUE TITLE
Adicionar códigos de serviço Correios

### ISSUE THREAD

**Issue by guiserinoli** [eloom/module-correios-frete#1]
Olá, primeiramente parabéns pelo módulo. Simples mas muito eficiente.

Gostaria de saber se há a possibilidade de, numa próxima versão, adicionar 2 códigos de serviços à lista no módulo. Seguem:
SEDEX com contrato - 03220
PAC com contrato - 03298

Agradeço desde já.

**Comment by eloom** [comment]
Olá @guiserinoli, boa tarde. Obrigado pelo elogio.

O objetivo do módulo é apenas realizar cotações e localização e trabalhar em sintonia com outros métodos de frete.

Colocamos os serviços 03220 e  03298.

Para atualização, basta executar "composer require eloom/module-correios-frete:1.0.1".

Abraço
