### ISSUE TITLE
Peso por gramas ou quilos sendo ignorado

### ISSUE THREAD

**Issue by ericsondesousa** [eloom/module-correios-frete#10]
No admin tem uma opção que permite escolher se o peso informado será em gramas ou quilo. No entanto, não encontrei no código nenhuma verificação que utilizasse esse parâmetro. E percebi que as cotações de fretes estão sendo enviadas no formato salvo no produto. Mas os Correios parece que fazem a cotação somente em gramas. 
Se a loja estiver configurada para informar o peso dos produtos no formato em Kg, a cotação fica errada. Porque a request envia para a API o atributo peso que deveria ser 1kg, 3kg, 5kg , no práticas a API dos Correios está recebendo como 1g, 3g, 5g, porque o módulo não converte kg em gramas.

![opção](https://github.com/eloom/module-correios-frete/assets/49835430/ca770176-ee39-425f-966b-813dcdcb7f2d)

**Comment by eloom** [comment]
@ericsondesousa, boa tarde.

Vou verificar a configuração.

Por padrão, há anos, nós usamos sempre em gramas e apenas numerais:

.300 para 300 gramas;
.900 para 900 gramas;
1000 para 1Kg.

**Comment by ericsondesousa** [comment]
Sim... Nós também...

Só que agora, se um produto tem 0.3kg (ou 300 gramas), na request tá indo que o produto tem 0.3 também, só que os Correios entendem que são 0.3gramas e não kilos... Acredito que a solução é bem simples. Basta verificar esse atributo no admin e se estiver como kg, multiplicar o valor do peso por 1000 antes de enviar para a API dos Correios.

**Comment by eloom** [comment]
Faz um favor, colocar um log na linha 207: $this->logger->info('TotalHeight', $this->totalHeight);

Estamos fazendo um cast para float, talvez esteja pegando apenas 1 casa decimal após o zero.

**Comment by eloom** [comment]
Faz um favor, colocar um log na linha 429: $this->logger->info('Peso ', $nVlPeso);

**Comment by ericsondesousa** [comment]
Então vamos lá..

Meu produto está cadastrado como 1kg e utilizando as dimensões padrões 2 de altura, 11 de largura e 16 de comprimento.
![image](https://github.com/eloom/module-correios-frete/assets/49835430/802eb22c-94d3-4130-8c36-e7950bc26a74)

Eu criei 2 dumps no arquivo da classe `Eloom\SdkCorreios\Endpoints\Preco`: um antes da requisição para saber quais valores estão indo no corpo da requisição e outro dump com a resposta da requisição.
![image](https://github.com/eloom/module-correios-frete/assets/49835430/9c3399da-9d64-493c-9219-ecbabe166ce6)


Então, quando faço a cotação, esses são os resultados:
![image](https://github.com/eloom/module-correios-frete/assets/49835430/b16fbfaa-fb51-45aa-a374-89e126dfa636)


Se eu mudar o peso do produto para 20kg, era para o cálculo de frete mudar consideravelmente. Mas os valores são os mesmos.
![image](https://github.com/eloom/module-correios-frete/assets/49835430/2da3524e-5f9b-46df-8e8c-84d223fce0ce)


Porque acontece isso? Porque os Correios estão esperando receber o valor em gramas. Mas a requisição está enviando o valor do produto como se fosse Kg. Ou seja, se um produto tem 20kg, a requisição deve enviar 20000gramas. Mas na prática a primeira requisição enviou como sendo 1grama e a segunda como sendo 20gramas. Por isso o cálculo continuou com o mesmo valor. Porque o peso mínimo dos Correios é 300 gramas. Então da forma atual está sempre calculando como 300 gramas.

Mas se eu fizer essa conversão de quilos para gramas, aí o cálculo é real.
Para a primeira requisição vou converter 1kg para 1000 gramas.
![image](https://github.com/eloom/module-correios-frete/assets/49835430/9e1a7b49-4154-4a2e-8187-2e65e7e758f5)

Pode ver que já subiu um pouco o preço. 

E se eu converter 20kg para 20.000 gramas.
![image](https://github.com/eloom/module-correios-frete/assets/49835430/843ada3b-eb0a-4e0a-aa61-c4f4a22e5790)

Agora faz muito mais sentido o preço cobrado.


A solução é: No arquivo de classe `Eloom\CorreiosFrete\Model\Carrier` , inserir o seguinte código:
![image](https://github.com/eloom/module-correios-frete/assets/49835430/0074a0d8-09e6-4bb8-ae28-b3345dd7e367)

Problema resolvido.

**Comment by ericsondesousa** [comment]
Na verdade, troquei a verificação para outro lugar

![image](https://github.com/eloom/module-correios-frete/assets/49835430/e091668c-6024-4b69-b536-e5c211f4a76b)

**Comment by ericsondesousa** [comment]
Fiz um Pull Request caso queiram.

https://github.com/eloom/module-correios-frete/pull/11

**Comment by eloom** [comment]
@ericsondesousa obrigado.

Não temos como colocar o pull request neste projeto porque há outro projeto "fonte" que gera o projeto fim. Vamos colocar seu código no projeto "fonte".
