### ISSUE TITLE
Incompatível com Magento vs2.4.5 PHP 8.1

### ISSUE THREAD

**Issue by Magenfy** [eloom/module-correios-frete#2]
Olá, Algum prazo de atualização para trabalhar com magento vs2.4.5 e PHP 8.1?

**Comment by eloom** [comment]
Olá @Magenfy o módulo está na fila para atualização pelo Composer, mas acredito que apenas para 2023.

Você poderá realizar uma instalação local no Magento. Não deve quebrar o código.
