### ISSUE TITLE
Frete Grátis com Regra de Carrinho não funciona

### ISSUE THREAD

**Issue by FauMJ** [eloom/module-correios-frete#3]
Configurei a opção de frete grátis e criei uma regra no carrinho para aplicar apenas para regiões determinadas mas não dá o desconto. A única forma que encontrei foi definir o valor da compra, na config do módulo mas, neste caso, vai dar frete grátis p qq um, independente de região, cep ou outras condições.

**Comment by eloom** [comment]
Olá @FauMJ, boa noite.

Houve um equívoco ao interpretar "definir o **valor da compra**". A configuração é "valor **máximo** para frete grátis". Quando o valor da compra atinge o valor configurado no módulo, o frete grátis é desativado para não dar prejuízo ao comerciante.

Esse módulo é uma migração do nosso módulo M1 e é usado há algum tempo, em várias lojas.

Me envia um print das configurações, somente com o que escreveu não é possível simularmos aqui.

Abraço
