### ISSUE TITLE
Dimensões de produto

### ISSUE THREAD

**Issue by guiserinoli** [eloom/module-correios-frete#5]
Olá!

Testando o módulo, reparamos que as dimensões dos produtos são ignoradas, sendo apenas considerados os valores padrão que são preenchidos nas configurações do módulo, e apenas o peso do produto em si.

**Comment by eloom** [comment]
@awakebrasil, boa tarde.

Estamos adaptando o módulo para informar os campos de medidas de forma dinâmica, assim como o da JadLog (https://github.com/eloom/module-jadlog-source/blob/main/src/module-jadlog/Model/Carrier.php). Até a próxima segunda-feira devemos liberar a versão 2.0.2.

**Comment by awakebrasil** [comment]
@eloom muito obrigado pelo rápido retorno, vou aguardar.
