### ISSUE TITLE
Api rest

### ISSUE THREAD

**Issue by valiati100** [eloom/module-correios-frete#6]
Correio tirou do ar a api soap mantendo apenas a api rest.

**Comment by eloom** [comment]
@valiati100 boa tarde.

Ficamos sabendo da migração recém na semana passada. Estamos migrando os módulos M1 e M2.

**Comment by valiati100** [comment]
Show de bola!

**Comment by irallajunior** [comment]
Alguma solução rápida, pra quem usa o módulo ellom?

**Comment by eloom** [comment]
@irallajunior boa tarde.

Eu desconheço outra solução Open Source.

A mudança nos pegou de surpresa, recém semana passada um de nossos clientes foi avisado. Estamos liberando o módulo para alguns clientes e corrigindo os problemas.

Houve uma mudança radical, não mudou somente do SOAP para REST como mudaram as assinaturas e retornos nos serviços.

Queremos liberar até quinta-feira o módulo aberto.

P.S. Agora somente quem têm contrato com Correios poderá realizar cotações e Prazo e Preço.

**Comment by albertobraschi** [comment]
Para mais informações:  https://ajuda.simplo7.com.br/hc/pt-br/articles/9177898907035-Veja-sobre-a-atualiza%C3%A7%C3%A3o-da-API-dos-Correios

Os Correios informaram que em 17/09/23 será descontinuada a integração atual chamada SOAP, afetando diretamente o serviço de rastreio, cotação de frete e prazo de envio das lojas. Portanto, é necessário substituir com urgência pela nova integração chamada REST.  

Não possuo contrato com os Correios e tenho CNPJ

Caso você ainda não possua contrato com os Correios e tenha CNPJ, os Correios agora exigem a necessidade deste contrato direto com eles - [Veja como contratar](https://ajuda.simplo7.com.br/hc/pt-br/articles/18753180536219)

Caso precise de suporte, envie um e-mail para comercioeletronico@correios.com.br

Após feito o contrato com os Correios, substitua com urgência a integração SOAP pela REST - [Veja como fazer](https://ajuda.simplo7.com.br/hc/pt-br/articles/18420971100059)

**Comment by eloom** [comment]
@albertobraschi boa tarde.

Acredito que ainda hoje devemos liberar o módulo.

Aqui https://www.correios.com.br/atendimento/developers/correios-developers constam todos os procedimentos.

**Comment by valiati100** [comment]
Nestas duas linhas, adicionei uma verificação para total compatibilidade com o PHP 8.2:

https://github.com/eloom/module-correios-frete/blob/8a50419f1bf49d07ca8c1b4d03a41ce692af5f0c/src/module-correios-frete/Model/Carrier.php#L139

https://github.com/eloom/module-correios-frete/blob/8a50419f1bf49d07ca8c1b4d03a41ce692af5f0c/src/module-correios-frete/Model/Carrier.php#L197

**Comment by valiati100** [comment]
Nestas duas linhas, adicionei uma verificação para total compatibilidade com o PHP 8.2:

https://github.com/eloom/module-correios-frete/blob/8a50419f1bf49d07ca8c1b4d03a41ce692af5f0c/src/module-correios-frete/Model/Carrier.php#L139

$this->fromZip = str_replace(array('-', '.'), '', trim($this->fromZip ?? ''));

https://github.com/eloom/module-correios-frete/blob/8a50419f1bf49d07ca8c1b4d03a41ce692af5f0c/src/module-correios-frete/Model/Carrier.php#L197

$this->toZip = str_replace(array('-', '.'), '', trim($this->toZip ?? ''));

**Comment by albertobraschi** [comment]
Alguem ja testou? 
Funciona bem?

**Comment by eloom** [comment]
Olá @valiati100, nós mudamos o "str_replace" por "preg_replace", assim contempla todas as versões PHP.

Infelizmente ainda não podemos usufruir das vantagens do PHP 8.2, algumas lojas ainda usam Magento 2.3.7.

Se quiser instalar a versão release, pode fazer: composer require eloom/module-correios-frete:2.0.0

Abraço

**Comment by eloom** [comment]
Ola @albertobraschi, boa noite.

Os serviços de Prazo, Preço e Tracking já estão funcionando.

Se quiser instalar a versão release, pode fazer: composer require eloom/module-correios-frete:2.0.0

Abraço

**Comment by albertobraschi** [comment]
@eloom Obrigado pelo retorno.

**Comment by eloom** [comment]
@albertobraschi, bom dia.

O Cartão de Postagem é para gerar a Bearer Authentication. É usado em todos os serviços privados.

**Comment by albertobraschi** [comment]
@eloom Entendi
Estou com a seguinte situação.
Instalei o plugin via composer, e acabei de validar as 3 informações do plugin direto no portal dos correios, https://cws.correios.com.br/ , e la funcionou tudo certo.
Porem, no magento fica o tempo todo dando erro de nao autorizado!
O que poderia estar causando isso?

Magento 2.4.3
Php 7.4
Eloom Correios 2.0, via composer

**Comment by eloom** [comment]
@albertobraschi, sofri muito com isso. O Header Basic Auth que os Correios gera era diferente do que eu gerava. Use essa ferramenta https://www.debugbear.com/basic-auth-header-generator para comparar o seu Basic Auth com o dos Correios. Nas chamadas dos serviços dos Correios pode copiar o Header Auth.

Se forem diferentes, o cliente terá de entrar em contato com a Agência e conferir os dados (ocorreu de um cliente nos passar login errado).

Se o Header Auth for igual, gere um novo  Código de Acesso da API aqui https://cws.correios.com.br/acesso-componentes.

**Comment by eloom** [comment]
@albertobraschi, ocorreu de outro cliente enviar o número errado do Cartão de Postagem, este é composto de 10 números e fica atrás do cartão.

**Comment by eloom** [comment]
@albertobraschi, pode fazer os testes direto neste zip em anexo.
- descompactar;
- rodar: composer install;
- no arquivo "test.php", colocar as credenciais;
- executar: php -f test.php

[sdk-correios-php.zip](https://github.com/eloom/module-correios-frete/files/12718270/sdk-correios-php.zip)

**Comment by eloom** [comment]
@albertobraschi, agora mesmo um cliente me havia passado o user para logar na API dos Correios e tudo funcionava.

Comparei os Header Basic Auth do serviço "[/v1/autentica/cartaopostagem](https://cws.correios.com.br/dashboard/pesquisa/35#/Token/tokenPorCartao)" e notei que eram diferentes.

Fazendo um reverso (decode) nesta ferramenta https://decodebase64.com/, descobri o user correto.

**Comment by albertobraschi** [comment]
@eloom Como voce fez?

**Comment by eloom** [comment]
@albertobraschi,

Usando o serviço "Token": /v1/autentica/cartaopostagem, é gerado 

Nesta URL https://cws.correios.com.br/dashboard/pesquisa#/Token/tokenPorCartao, faça uma simulação de autenticação pelo Cartão de Postagem em "Try it out". Informe o Cartão de Postagem e execute.

No response virá um exemplo de chamada em Curl (imagem em anexo), com o "Authorization: Basic".

--

Para descobrir o user, faça um reverso (decode) nesta ferramenta https://decodebase64.com/, copiando o token "Authorization: Basic".

Para conferir se seu user bate com o que o Correios gerou, informe o user e senha nesta ferramenta:  https://www.debugbear.com/basic-auth-header-generator. Ela irá gerar um  "Authorization: Basic"
![token](https://github.com/eloom/module-correios-frete/assets/16610181/e89ff14b-93b7-498e-a426-08c2c3ab9fbe)

**Comment by albertobraschi** [comment]
@eloom é o usuario e senha do portal dos correios que esta valendo, e nao os dados antigos?

**Comment by eloom** [comment]
@albertobraschi, os serviços usam o Basic Auth (user, código de acesso) "https://en.wikipedia.org/wiki/Basic_access_authentication" inicialmente, e em sequência, o Bearer Authentication "https://swagger.io/docs/specification/authentication/bearer-authentication/" para acessar os serviços. O Bearer é gerado com o código de postagem, logo após ser autenticado pelo Basic Auth.

Se quiser enviar o user, password, código de acesso (40 caracteres) e cartão de postagem para esse email "rodrigo.sanders@eloom.com.br", testo aqui e vejo o que pode ser.

**Comment by albertobraschi** [comment]
@eloom eu usei aquele seu script, test.php, e ja retornou o token; vlw

**Comment by eloom** [comment]
@albertobraschi, se retornou o token está tudo certo. É só informar o user, código de acesso e cartão no magento e funcionará.

* quando geramos um novo código de acesso para as API, demora uns 5 minutos pra funcionar;
* essa semana iremos adicionar novos códigos de serviços que recebemos.

**Comment by albertobraschi** [comment]
@eloom agora com o usuario resolvido, a integração dos correios foi bem sucedida! obrigado pela ajuda
