### ISSUE TITLE
Configuração do módulo e Erro ao Rastrear WSDL

### ISSUE THREAD

**Issue by fabiofbra** [eloom/module-correios-frete#8]
Instalei o módulo 2.0.2 no Magento 2.4.3.

Nas configurações do módulo, quais seriam os códigos para:
Usuário: usuário sigep?
Código de Acesso: senha sigep?

Estou recebendo esse erro, ao registrar um localizador em uma venda e clicar para rastrear:
Error: Class 'Eloom\CorreiosFrete\Model\Mage' not found in /cloudclusters/magento/vendor/eloom/module-correios-frete/src/module-correios-frete/Model/Carrier.php:486

Qual ajuste precisa ser feito?

**Comment by eloom** [comment]
@fabiofbra, tudo bem?

Agora é preciso que o estabelecimento tenha convênio firmado com os Correios. Ao firmar convênio, o estabelecimento receberá o usuário/senha.

Aqui (https://www.correios.com.br/atendimento/developers/correios-developers) têm todas as infos.

Infelizmente, agora, usar Correios somente se tiver um plano contratado.
